name: bht-labs-mcp-server
region: nyc
services:
- name: mcp-server
  dockerfile_path: Dockerfile
  source_dir: /
  git:
    repo_clone_url: file:///Users/supabowl/Downloads/Cursor/MCP%20Client%20-%20Alejandro%20AO/mcp-client-python/app-platform
    branch: master
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  health_check:
    http_path: /health
  routes:
  - path: /
  envs:
  - key: MCP_AUTH_KEY
    value: ee1008da08d0fc21cc0b744d64feebc0
    scope: RUN_AND_BUILD_TIME
  - key: MCP_DATA_DIR
    value: /app/data
    scope: RUN_AND_BUILD_TIME