name: bht-labs-mcp-server-simple
region: nyc
services:
- name: mcp-server
  dockerfile_path: Dockerfile
  source_dir: /
  http_port: 8080
  instance_size_slug: basic-xxs
  health_check:
    http_path: /health
  envs:
  - key: MCP_AUTH_KEY
    value: ea7b0fb144dfee03c8e76cfd41bc8b49
    scope: RUN_AND_BUILD_TIME
  - key: MCP_DATA_DIR
    value: /app/data
    scope: RUN_AND_BUILD_TIME
  - key: GRAPHLIT_ORGANIZATION_ID
    value: 3e122b27-4534-4893-aadd-5d5cb83337f7
    scope: RUN_AND_BUILD_TIME
  - key: GRAPHLIT_ENVIRONMENT_ID
    value: a2959835-fd03-4653-9395-ac921421c93f
    scope: RUN_AND_BUILD_TIME
  - key: GRAPHLIT_JWT_SECRET
    value: "RizYP09Mn+tsnXUSLCrX+6g4nmVhF/tRK5Wch0JesGg="
    scope: RUN_AND_BUILD_TIME
  - key: NODE_OPTIONS
    value: "--max-old-space-size=2048"
    scope: RUN_AND_BUILD_TIME
  github:
    repo: jhillbht/bht-labs
    branch: minimal-working
    deploy_on_push: true
  routes:
  - path: /
