name: bht-labs-mcp-server-simple
region: nyc
services:
- name: mcp-server
  source_dir: /
  dockerfile_path: Dockerfile
  http_port: 8080
  instance_size_slug: basic-xs
  health_check:
    http_path: /health
  envs:
  - key: MCP_AUTH_KEY
    value: ea7b0fb144dfee03c8e76cfd41bc8b49
    scope: RUN_AND_BUILD_TIME
  - key: MCP_DATA_DIR
    value: /app/data
    scope: RUN_AND_BUILD_TIME
  routes:
  - path: /
